In [1]:
import torch
torch.__version__

'1.12.0+cu116'

In [3]:
torch.cuda.is_available()

True

## Tensor的创建

In [4]:
torch.tensor([[1., -1], [1., -1]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [7]:
import numpy as np
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [8]:
torch.Tensor([[1., -1], [1., -1]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [9]:
torch.Tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [15]:
torch.tensor(2)

tensor(2)

In [12]:
torch.tensor([1])

tensor([1])

In [19]:
torch.Tensor(2)

tensor([1.0415e-37, 4.5907e-41])

## 张量的方法和属性

In [31]:
t1 = torch.tensor([[1]])
t1.item()

1

In [36]:
t2 = torch.tensor([[[1, 2], [3, 4]]])
t2.numpy()

array([[[1, 2],
        [3, 4]]], dtype=int64)

In [37]:
t2.size()

torch.Size([1, 2, 2])

In [41]:
t2.size(-1)

2

In [42]:
t2.view(1,1,4)

tensor([[[1, 2, 3, 4]]])

In [44]:
t2.view((1,1,4))

tensor([[[1, 2, 3, 4]]])

In [43]:
t2.view(4)

tensor([1, 2, 3, 4])

In [47]:
t3 = torch.tensor(np.arange(12).reshape(3,4))
t3

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [48]:
t3.max()

tensor(11, dtype=torch.int32)

In [53]:
t3.float().std()

tensor(3.6056)

In [54]:
t4 = torch.tensor(np.arange(24).reshape(2,3,4))
t4

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [55]:
t4.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

In [56]:
t4.transpose(0,1)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [60]:
t4

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [61]:
t4[:,1,1]

tensor([ 5, 17], dtype=torch.int32)

In [62]:
t4[1,:,1]

tensor([13, 17, 21], dtype=torch.int32)

In [63]:
t4[1,1,:]

tensor([16, 17, 18, 19], dtype=torch.int32)

## Tensor 数据类型

In [64]:
torch.ones([2,3], dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [66]:
torch.ones([2,3], dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1]])

## Tensor其他操作

### Tensor 运算

In [10]:
t1 = torch.rand(5,3)
t1

tensor([[0.5904, 0.3949, 0.5979],
        [0.9546, 0.3873, 0.6885],
        [0.1685, 0.6350, 0.1108],
        [0.7023, 0.6288, 0.1350],
        [0.6526, 0.7522, 0.2084]])

In [11]:
t2 = torch.rand(5,3)
t2

tensor([[0.7254, 0.4489, 0.4206],
        [0.3529, 0.2566, 0.3654],
        [0.5813, 0.6187, 0.5439],
        [0.4546, 0.7020, 0.3207],
        [0.5079, 0.2081, 0.5410]])

In [12]:
t1 + t2

tensor([[1.3158, 0.8438, 1.0185],
        [1.3075, 0.6439, 1.0539],
        [0.7498, 1.2536, 0.6547],
        [1.1569, 1.3308, 0.4558],
        [1.1605, 0.9603, 0.7494]])

In [15]:
t1.add(t2) # 不会对t1本身做出变化

tensor([[1.3158, 0.8438, 1.0185],
        [1.3075, 0.6439, 1.0539],
        [0.7498, 1.2536, 0.6547],
        [1.1569, 1.3308, 0.4558],
        [1.1605, 0.9603, 0.7494]])

In [16]:
t1

tensor([[0.5904, 0.3949, 0.5979],
        [0.9546, 0.3873, 0.6885],
        [0.1685, 0.6350, 0.1108],
        [0.7023, 0.6288, 0.1350],
        [0.6526, 0.7522, 0.2084]])

In [17]:
t1.add_(t2) # 产生就地修改

tensor([[1.3158, 0.8438, 1.0185],
        [1.3075, 0.6439, 1.0539],
        [0.7498, 1.2536, 0.6547],
        [1.1569, 1.3308, 0.4558],
        [1.1605, 0.9603, 0.7494]])

In [18]:
t1

tensor([[1.3158, 0.8438, 1.0185],
        [1.3075, 0.6439, 1.0539],
        [0.7498, 1.2536, 0.6547],
        [1.1569, 1.3308, 0.4558],
        [1.1605, 0.9603, 0.7494]])

In [19]:
torch.cuda.is_available()

True

In [22]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [24]:
t1.to(device)

tensor([[1.3158, 0.8438, 1.0185],
        [1.3075, 0.6439, 1.0539],
        [0.7498, 1.2536, 0.6547],
        [1.1569, 1.3308, 0.4558],
        [1.1605, 0.9603, 0.7494]], device='cuda:0')

In [26]:
t2 = torch.rand((5,3), device=device)
t2

tensor([[0.2704, 0.9654, 0.8469],
        [0.1289, 0.7989, 0.0961],
        [0.6773, 0.9391, 0.5091],
        [0.4751, 0.2946, 0.5941],
        [0.6228, 0.6008, 0.3109]], device='cuda:0')